import Image from "next/image";
import style from "./Layout.module.css";
import Header from "@/component/header/header";
import Footer from "@/component/footer/footer";
export const metadata = {
  title: "PLP E-commerce Task",
  description: "Generated by PLP",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }} className={style.body}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
